FROM microsoft/dotnet-framework:4.6.2

RUN powershell -Command Add-WindowsFeature Web-Server & \
    powershell -Command Add-WindowsFeature NET-Framework-45-ASPNET & \
    powershell -Command Add-WindowsFeature Web-Asp-Net45 & \
    %windir%\System32\inetsrv\appcmd set apppool /apppool.name:DefaultAppPool /managedRuntimeVersion:v4.0 & \
    powershell -Command Remove-Item -Recurse C:\inetpub\wwwroot\*

RUN mkdir c:\shared
RUN mkdir c:\shared\content
RUN mkdir c:\shared\script

ADD spinner.exe /
ADD ServiceMonitor.exe /

EXPOSE 80

SHELL ["powershell"]

ENTRYPOINT ["powershell", "c:\\shared\\script\\script.ps1"]
